# Generated by Django 5.1.3 on 2026-02-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Custom_Dashboard",
        ),
    ]
