# Generated by Django 5.1.3 on 2026-02-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custom_dashboard",
            name="created_at",
        ),
        migrations.AddField(
            model_name="custom_dashboard",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="custom_dashboard",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
